services:
  - type: web
    name: rohit-drm-player
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PORT
        value: "10000"